name: Generate Report
on:
  schedule:
    - cron: "30 20 * * 3"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://rendiciones.vercel.app/api/cron' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
